### ISSUE TITLE
sources

### ISSUE THREAD

**Issue by zebardy** [miyagawa/cpanfile#35]
I would like to add an equivalent to gemfiles sources elements. The idea being that the sources specified would be equivalent to specifying a mirror list to cpanm. The usecase for this is where you have an internal darkpan supplying non public libraries used by your project. The cpanfile for the project can then specify the darkpan or darkpans that are required for the project. This could also be interesting in combination with stratopan. 

I'd be interested to hear thoughts regarding the inclusion of an element like this, and what format/structure it should take in the cpanfile.

**Comment by miyagawa** [comment]
it's implemented in `mirror` syntax in #22.

But there's no client (as of I know) that understands this.

**Comment by zebardy** [comment]
Ace thanks :)
