### ISSUE TITLE
No way to enforce ordering of required module installation

### ISSUE THREAD

**Issue by nhr** [miyagawa/cpanfile#42]
I've been poking around trying to find an example of how to do this, but I can't sort it out.

I have a Perl project that uses a cpanfile to define a list of prerequisites. One of the prerequisites is PDF::API2::Simple, which itself depends upon Module::Install.

I assumed that the `requires` lines in the cpanfile are processed in line-order, meaning that as long as the Module::Install line preceded the PDF::API2::Simple line, things would work correctly.

However, this is not the case - the cpanm utility appears to process the lines in random order, and so sometimes the process works but other times it doesn't.

So the question is, _within a single phase_, is there any way to enforce the ordering of module installations between cpanm and the cpanfile?

**Comment by miyagawa** [comment]
> I assumed that the requires lines in the cpanfile are processed in line-order, meaning that as long as the Module::Install line preceded the PDF::API2::Simple line, things would work correctly.

It is parsed in line-order, but once it's handed off to cpanm it is converted to CPAN::Meta::Prereqs which will retain the dependencies in a hash, which means the order is random.

So the answer to that is No.

What is the thing you're trying to accomplish, though?

**Comment by miyagawa** [comment]
PDF::API2::Simple is just a pretty bad dist that doesn't have `inc/` although it uses Module::Install. It really has to be fixed there. There's no easy workaround for this, except you run `cpanm Module::Install` before running the cpanfile-based run.

**Comment by nhr** [comment]
Thanks for the explanation. I'll figure out a way to get Module::Install in place before processing the cpanfile. To answer the question of what I'm trying to do, I am working on modifying [my app](https://github.com/nhr/swn) to [build correctly](https://github.com/openshift/sti-perl) for deployment on an [OpenShift](https://github.com/openshift/origin) cluster.
