### ISSUE TITLE
validate contradicting version specifications

### ISSUE THREAD

**Issue by XSven** [miyagawa/cpanfile#56]
To me this

```
on 'runtime' => sub {
  requires 'Foo', '== 1.1';
  requires 'Foo', '== 1.0';
};
```
is a contradicting version specification and processing such a cpanfile using `Module::CPANfile` should at least raise a warning. Unfortunately `Module::CPANfile::Environment::parse()` does not detect this mistake and `Module::CPANfile::Prereqs::specs()` implements the "last wins strategy". Any suggestion at what place more strict validation and/or a different specs selection strategy could be hooked in, is very much appreciated.

**Comment by miyagawa** [comment]
Module::CPANfile is pretty much a syntax layer to produce data that's defined in CPAN::Meta, and if anything, a semantic data processing should occur there, or by an application that uses the data.

**Comment by XSven** [comment]
Even if that was the idea it is not implemented like that. The specs that are passed to `CPAN::Meta::Prereqs::new()` are already flattened/cleaned by `Module::CPANfile::Prereqs::specs()` that means `CPAN::Meta::Prereqs` can not do any semantic data processing because it has not got all the information.

**Comment by miyagawa** [comment]
ah, I missed that it occurs within the module. I think it makes sense to merge these requirements if there're multiple lines for the same module.

**Comment by XSven** [comment]
Are you going to re-open this issue? If you explain your merge strategy and if we find a consensus I could create a pull request.

**Comment by miyagawa** [comment]
you could simply merge the values by a comma.
