### ISSUE TITLE
Test failing when RJBS/CPAN-Meta-Requirements-2.142.tar.gz is installed

### ISSUE THREAD

**Issue by andk** [miyagawa/cpanfile#57]
Sample fail reports:

- my oldest: http://www.cpantesters.org/cpan/report/2f97ae98-f09e-11ed-93bf-deca0fb09b43
- my most recent ATM: http://www.cpantesters.org/cpan/report/c29c505e-0dd1-11ee-9d28-6c554fd2e7f5

@rjbs

**Comment by miyagawa** [comment]
seems fixed with https://github.com/Perl-Toolchain-Gang/CPAN-Meta-Requirements/pull/38

**Comment by miyagawa** [comment]
This is now fixed with CPAN::Meta::Requirements 2.143.
